---
# tasks file for prepare

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - haproxy
    - keepalived
    - net-tools

- name: Stop service ufw, if started
  ansible.builtin.service:
    name: ufw
    state: stopped

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Allow ssh connection 
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "22"
    jump: ACCEPT


- name: Allow ssh connection 
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: "{{ item.frontend_port }}"
    jump: ACCEPT
  loop: "{{ upstreams }}" 