---
# tasks file for prepare

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - haproxy
    - keepalived
    - net-tools

- name: Stop service ufw, if started
  ansible.builtin.service:
    name: ufw
    state: stopped

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "22"
      - "80"
      - "443"
    jump: ACCEPT